INSERT INTO publisher (name) VALUES ('Abdo Publishing Company'),
                                    ('Ace'),
                                    ('Ace Books'),
                                    ('Broadway Books'),
                                    ('Farrar Straus Giroux'),
                                    ('Gramercy Books'),
                                    ('Harper Perennial'),
                                    ('Large Print Press'),
                                    ('NAL'),
                                    ('New Directions'),
                                    ('Penguin Books'),
                                    ('Penguin Classics'),
                                    ('Random House Trade Paperbacks'),
                                    ('Scribner'),
                                    ('Simon & Schuster'),
                                    ('Vintage'),
                                    ('William Morrow Paperbacks');
INSERT INTO book (title, ISBN, page_count, publication_date, publisher_id,
                  description, price, quantity) VALUES ('Bill Bryson''s African Diary', '0767915062', 55, '12/3/2002', 4, '“Here is a man who suffers so his readers can laugh.” — Daily TelegraphBill Bryson travels to Kenya in support of CARE International. All royalties and profits go to CARE International.Bryson visits Kenya at the invitation of CARE International, the charity dedicated to eradicating poverty. Kenya is a land of contrasts, with famous game reserves and a vibrant culture. It also provides plenty to worry a traveller like Bill Bryson, fixated as he is on the dangers posed by snakes, insects and large predators. It is also a country with many serious problems: refugees, AIDS, drought, and grinding poverty. The resultant diary, though short in length, contains the trademark Bryson stamp of wry observation and curious insight.', 4.99, 19),
                                                       ('In a Sunburned Country', '0767903862', 335, '5/15/2001', 4, 'Every time Bill Bryson walks out the door memorable travel literature threatens to break out. His previous excursion up, down, and over the Appalachian Trail (well, most of it) resulted in the sublime national bestseller A Walk in the Woods. Now he has traveled across the world and all the way Down Under to Australia, a shockingly under-discovered country with the friendliest inhabitants, the hottest, driest weather, and the most peculiar and lethal wildlife to be found on the planet. In a Sunburned Country is his report on what he found there--a deliciously funny, fact-filled, and adventurous performance by a writer who combines humor, wonder, and unflagging curiosity.Australia is a country that exists on a vast scale. It is the only island that is also a continent and the only continent that is also a country. Despite being the most desiccated, infertile, and climatically aggressive of all inhabited continents, it teems with life. In fact, Australia has more things that can kill you in extremely nasty ways than anywhere else: sharks, crocodiles, the ten most deadly poisonous snakes on the planet, fluffy yet toxic caterpillars, seashells that actually attack you, and the unbelievable box jellyfish (don''t ask). The dangerous riptides of the sea and the sun-baked wastes of the outback both lie in wait for the unwary. It''s one tough country.Bill Bryson adores it, of course, and he takes his readers on a rollicking ride far beyond the beaten tourist path. Here is a place where interesting things happen all the time, from a Prime Minister lost--yes, lost--while swimming at sea to Japanese cult members who may have set off an atomic bomb (sic) entirely unnoticed on their 500,000-acre property in the great western desert.Wherever he goes (and Bryson goes just about everywhere) he finds Australians who are cheerful, extroverted, and unfailingly obliging--the beaming products of a land with clean, safe cities, cold beer, and constant sunshine. On occasion the Aborigines, a remote and mysterious race with a tragic history, make a haunting appearance in this book. But by and large Australia is an immense and fortunate land, and it has found in Bill Bryson its perfect guide. Published just in time for the 2000 Olympics in Sydney, In a Sunburned Country offers the best of all possible introductions to what may well be the best of all possible nations. Even with those jellyfish.', 4.99, 4),
                                                       ('Notes from a Small Island', '0380727501', 324, '5/28/1997', 17, 'Before New York Times bestselling author Bill Bryson wrote The Road to Little Dribbling, he took this delightfully irreverent jaunt around the unparalleled floating nation of Great Britain, which has produced zebra crossings, Shakespeare, Twiggie Winkie''s Farm, and places with names like Farleigh Wallop and Titsey.', 8.79, 6),
                                                       ('The Heidi Chronicles: Uncommon Women and Others & Isn''t It Romantic', '0679734996', 249, '7/2/1991', 16, 'The graduating seniors of a Seven Sisters college, trying to decide whether to pattern  themselves after Katharine Hepburn or Emily Dickinson. Two young women besieged by  the demands of mothers, lovers, and careers—not to mention a highly persistent telephone  answering machine—as they struggle to have it all. A brilliant feminist art historian  trying to keep her bearings and her sense of humor on the elevator ride from the  radical sixties to the heartless eighties.Wendy Wasserstein''s characters are so  funny, so many-sided, and so real that we seem to know them from their Scene One  entrances, though the places they go are invariably surprising. And these three plays—Uncommon  Women and Others, Isn''t It Romantic, and the Pulitzer Prize-winning The Heidi Chronicles—manage  to engage us heart, mind, and soul on such a deep and lasting level that they are  already recognized as classics of the modern theater.', 5.29, 0),
                                                       ('Anna Karenina', '0143035002', 838, '5/31/2004', 12, 'The must-have Pevear and Volokhonsky translation of one of the greatest Russian novels ever written Described by William Faulkner as the best novel ever written and by Fyodor Dostoevsky as “flawless,” Anna Karenina tells of the doomed love affair between the sensuous and rebellious Anna and the dashing officer, Count Vronsky. Tragedy unfolds as Anna rejects her passionless marriage and thereby exposes herself to the hypocrisies of society. Set against a vast and richly textured canvas of nineteenth-century Russia, the novel''s seven major characters create a dynamic imbalance, playing out the contrasts of city and country life and all the variations on love and family happiness. While previous versions have softened the robust and sometimes shocking qualities of Tolstoy''s writing, Pevear and Volokhonsky have produced a translation true to his powerful voice. This authoritative edition, which received the PEN Translation Prize and was an Oprah Book Club™ selection, also includes an illuminating introduction and explanatory notes. Beautiful, vigorous, and eminently readable, this Anna Karenina will be the definitive text for fans of the film and generations to come. This Penguin Classics Deluxe Edition also features French flaps and deckle-edged paper.For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators.', 8.79, 3),
                                                       ('Wrinkles in Time', '0380720442', 360, '10/1/1994', 7, 'In April 1992, a discovery was made that changed the way we view the world. Dr. George Smoot, distinguished cosmologist and adventurer, whose quest for cosmic knowledge had taken him from the Brazilian rain forest to the South Pole unveiled his momentous discovery, bringing to light the very nature of the universe. For anyone who has ever looked up at the night sky and wondered, for anyone who has ever longed to pull aside the fabric of the universe for a glimpse of what lies behind it. Wrinkles in Time is the story of Smoot''s search to uncover the cosmic seeds of the universe.Wrinkles in Time is the Double Helix of cosmology, an intimate look at the inner world of men and women who ask. "Why are we here?"It tells the story of George Smoot''s dogged pursuit of the cosmic wrinkles in the frozen wastes of Antarctica, on mountaintops, in experiments borne aloft aboard high-altitude balloons, U-2 spy planes, and finally a space satellite.Wrinkles in Time presents the hard science behind the structured violence of the big bang theory through breathtakingly clear, lucid images and meaningful comparisons. Scientists and nonscientists alike can follow with rapt attention the story of how, in a fiery creation, wrinkles formed in space ultimately to become stars, galaxies, and even greater delicate structures. Anyone can appreciate the implications of a universe whose end is written in its beginnings - whose course developed according to a kind of cosmic DNA, which guided the universe from simplicity and symmetry to ever-greater complexity and structure.As controversial as it may seem today, Wrinkles in Time reveals truths that, in an earlier century, would have doomed its proclaimers to the fiery stake. For four thousand years some people have accepted the Genesis account of cosmic origin; for most of this century, scientists debated two rival scientific explanations known as the steady state and big bang theories. And now, Wrinkles in Time tells what really happened.', 5.58, 2),
                                                       ('Treasure Island', '0517221144', 272, '9/3/2002', 6, null, 4.99, 1),
                                                       ('Treasure Island (Great Illustrated Classics)', '1577658051', 232, '1/31/2006', 1, null, 4.89, 13),
                                                       ('Stranger in a Strange Land', '0441788386', 528, '10/1/1991', 2, null, 199.93, 8),
                                                       ('To Sail Beyond the Sunset', '0441748600', 434, '6/1/1988', 3, 'Bestselling author Robert A. Heinlein''s autobiographical masterpiece—a wondrous return to the alternate universes that all Heinlein fans have come to know and love.Maureen Johnson, the somewhat irregular mother of Lazarus Long, wakes up in bed with a man and a cat. The cat is Pixel, well-known to readers of the New York Times bestseller The Cat Who Walks Through Walls. The man is a stranger to her, and besides that, he is dead...Filled with the master''s most beloved characters, To Sail Beyond the Sunset broadens and enriches Heinlein''s epic visions of time and space, life and death, love and desire...', 5.29, 4),
                                                       ('Lincoln at Gettysburg: The Words That Remade America', '0671867423', 317, '6/12/1993', 15, 'The power of words has rarely been given a more compelling demonstration than in the Gettysburg Address. Lincoln was asked to memorialize the gruesome battle. Instead, he gave the whole nation "a new birth of freedom"in the space of a mere 272 words. His entire life and previous training, and his deep political experience went into this, his revolutionary masterpiece.  By examining both the address and Lincoln in their historical moment and cultural frame, Wills breathes new life into words we thought we knew, and reveals much about a president so mythologized but often misunderstood. Wills shows how Lincoln came to change the world and to effect an intellectual revolution, how his words had to and did complete the work of the guns, and how Lincoln wove a spell that has not yet been broken.', 4.99, 4),
                                                       ('Underworld', '0684848155', 827, '7/9/1998', 14, 'Here are photographs - in black-and-white and in color - of men and women, clothed and unclothed, taken from the 1880s through the 1990s by Jacques-Henri Lartigue, Imogen Cunningham, Steven Meisel, Man Ray, Bettina Rheims, Helmut Newton, Sally Mann, Kurt Markus, Jerome Zerbe, Ellen von Unwerth, Andre Kertesz, Arthur Elgort, Louise Dahl-Wolfe, Herbert List, Eve Arnold, Brassai, and sixty-four others.', 35.7, 16),
                                                       ('Leviathan', '0140178139', 275, '9/1/1993', 11, null, 4.99, 4),
                                                       ('The Red Notebook: True Stories', '0811214982', 104, '6/17/2002', 10, 'The Red Notebook brings together in one volume all of Paul Auster''s short, true-life stories—a remarkable collection of tales that documents the curious, miraculous, and sometimes catastrophic turns of everyday reality.', 5.29, 11),
                                                       ('The Lovely Bones', '159413023X', 532, '4/1/2004', 8, 'Once in a generation a novel comes along that taps a vein of universal human experience, resonating with readers of all ages. THE LOVELY BONES is such a book -- a #1 bestseller celebrated at once for its artistry, for its luminous clarity of emotion, and for its astonishing power to lay claim to the hearts of millions of readers around the world."My name was Salmon, like the fish; first name, Susie. I was fourteen when I was murdered on December 6, 1973."So begins the story of Susie Salmon, who is adjusting to her new home in heaven, a place that is not at all what she expected, even as she is watching life on earth continue without her -- her friends trading rumors about her disappearance, her killer trying to cover his tracks, her grief-stricken family unraveling. Out of unspeakable tragedy and loss, THE LOVELY BONES succeeds, miraculously, in building a tale filled with hope, humor, suspense, even joy.', 4.99, 13),
                                                       ('Anthem', '0452281253', 105, '12/1/1999', 9, 'Ayn Rand''s classic tale of a dystopian future of the great “We”—a world that deprives individuals of a name or independence—that anticipates her later masterpieces, The Fountainhead and Atlas Shrugged.They existed only to serve the state. They were conceived in controlled Palaces of Mating. They died in the Home of the Useless. From cradle to grave, the crowd was one—the great WE.In all that was left of humanity there was only one man who dared to think, seek, and love. He lived in the dark ages of the future. In a loveless world, he dared to love the woman of his choice. In an age that had lost all trace of science and civilization, he had the courage to seek and find knowledge. But these were not the crimes for which he would be hunted. He was marked for death because he had committed the unpardonable sin: He had stood forth from the mindless human herd. He was a man alone. He had rediscovered the lost and holy word—I.“I worship individuals for their highest possibilities as individuals, and I loathe humanity, for its failure to live up to these possibilities.”—Ayn Rand', 5.29, 16),
                                                       ('Sailing Alone Around the Room: New and Selected Poems', '0375755195', 192, '9/17/2002', 13, '"High, most encouraging tidings"--that is how Billy Collins, the widely read and widely acclaimed poet, describes the music in his poem about the gospel singing group The Sensational Nightingales. The same phrase applies, just as joyfully, to the arrival of Sailing Alone Around the Room, a landmark collection of new and selected poems by this Guggenheim Fellow, NPR contributor, New York Public Library "Literary Lion,"and incomparably popular performer of his own good works.  From four earlier collections, which have secured for him a national reputation, Collins offers the lyric equivalent of an album of Greatest Hits. In "Forgetful-ness,"memories of the contents of a novel "retire to the southern hemisphere of the brain,  to a little fishing village where there are no phones."In "Osso Buco,"a poem about gustatory pleasure, the "lion of content-ment"places a warm heavy paw on the poet''s chest. In "Marginalia,"he catalogs the scrawled comments of books'' previous readers: "''Absolutely,'' they shout to Duns Scotus and James Baldwin.  ''Yes.'' ''Bull''s-eye.''  ''My man!'' "And he also serves us a generous portion of new poems, including "Man Listening to Disc,"a jazz trip with headphones, and "The Iron Bridge,"a wildly speculative, moving elegy.Whether old or new, these poems will catch their readers by exhilarating surprise. They may begin with irony and end in lyric transcendence. They may open with humor and close with grief. They may, and often do, begin with the everyday and end with infinity. Wise, funny, sad, stealthy, and always perfectly clear, these poems will not be departing for that little fishing village with no phones for a long, long time. Billy Collins, possessed of a unique lyric voice, is one of American poetry''s most sensational nightingales.', 5.29, 7),
                                                       ('The Natural', '0374502005', 231, '7/7/2003', 5, 'Biting, witty, provocative, and sardonic, Bernard Malamud''s The Natural is widely considered to be the premier baseball novel of all time. It tells the story of Roy Hobbs--an athlete born with rare and wondrous gifts--who is robbed of his prime playing years by a youthful indiscretion that nearly consists him his life. But at an age when most players are considering retirement, Roy reenters the game, lifting the lowly New York Knights from last place into pennant contention and becoming an instant hero in the process. Now all he has to worry about is the fixers, the boss, the slump, the jinx, the fans...and the dangerously seductive Memo Paris, the one woman Roy can''t seem to get out of his mind', 5.29, 16),
                                                       ('Memoirs of a Geisha', '0099771519', 497, '6/4/1998', 16, 'Her memoirs conjure up the perfection and the ugliness of life behind rice-paper screens, where young girls learn the arts of geisha - dancing and singing, how to wind the kimono, how to walk and pour tea, and how to beguile the land''s most powerful men.', 6.29, 1),
                                                       ('1776', '0140481397', 192, '11/18/1976', 11, 'America''s beloved and distinguished historian presents, in a book of breathtaking excitement, drama, and narrative force, the stirring story of the year of our nation''s birth, 1776, interweaving, on both sides of the Atlantic, the actions and decisions that led Great Britain to undertake a war against her rebellious colonial subjects and that placed America''s survival in the hands of George Washington.In this masterful book, David McCullough tells the intensely human story of those who marched with General George Washington in the year of the Declaration of Independence—when the whole American cause was riding on their success, without which all hope for independence would have been dashed and the noble ideals of the Declaration would have amounted to little more than words on paper.  Based on extensive research in both American and British archives, 1776 is a powerful drama written with extraordinary narrative vitality. It is the story of Americans in the ranks, men of every shape, size, and color, farmers, schoolteachers, shoemakers, no-accounts, and mere boys turned soldiers. And it is the story of the King''s men, the British commander, William Howe, and his highly disciplined redcoats who looked on their rebel foes with contempt and fought with a valor too little known.  Written as a companion work to his celebrated biography of John Adams, David McCullough''s 1776 is another landmark in the literature of American history.', 4.99, 10);
INSERT INTO author (first_name, last_name) VALUES ('A.J.', 'McAllister'),
                                                  ('Alice', 'Sebold'),
                                                  ('Arthur', 'Golden'),
                                                  ('Ayn', 'Rand'),
                                                  ('Bernard', 'Malamud'),
                                                  ('Bill', 'Bryson'),
                                                  ('Billy', 'Collins'),
                                                  ('Deidre', 'S. Laiken'),
                                                  ('Don', 'DeLillo'),
                                                  ('Garry', 'Wills'),
                                                  ('George', 'Smoot'),
                                                  ('Keay', 'Davidson'),
                                                  ('Kevin', 'Baker'),
                                                  ('Larissa', 'Volokhonsky'),
                                                  ('Leo', 'Tolstoy'),
                                                  ('Milo', 'Winter'),
                                                  ('Paul', 'Auster'),
                                                  ('Peter', ' Stone'),
                                                  ('Richard', 'Pevear'),
                                                  ('Robert', 'A. Heinlein'),
                                                  ('Robert', 'Louis Stevenson'),
                                                  ('Sherman', 'Edwards'),
                                                  ('Wendy', 'Wasserstein');
INSERT INTO book_author (book_id, author_id) VALUES (1, 6),
                                                    (2, 6),
                                                    (3, 6),
                                                    (4, 23),
                                                    (5, 15),
                                                    (5, 19),
                                                    (5, 14),
                                                    (6, 11),
                                                    (6, 12),
                                                    (7, 21),
                                                    (7, 16),
                                                    (8, 1),
                                                    (8, 21),
                                                    (8, 8),
                                                    (9, 20),
                                                    (10, 20),
                                                    (11, 10),
                                                    (12, 9),
                                                    (13, 17),
                                                    (14, 17),
                                                    (15, 2),
                                                    (16, 4),
                                                    (17, 7),
                                                    (18, 5),
                                                    (18, 13),
                                                    (19, 3),
                                                    (20, 18),
                                                    (20, 22);
INSERT INTO category (name) VALUES ('Africa'),
                                   ('American'),
                                   ('Antiques & Collectibles'),
                                   ('Australia & Oceania'),
                                   ('Civil War Period (1850-1877)'),
                                   ('Classics'),
                                   ('Collections, Catalogs, Exhibitions'),
                                   ('Drama'),
                                   ('Essays & Travelogues'),
                                   ('Fiction'),
                                   ('General'),
                                   ('Historical'),
                                   ('History'),
                                   ('Juvenile Fiction'),
                                   ('Juvenile Nonfiction'),
                                   ('Literary'),
                                   ('Literary Criticism'),
                                   ('Photography'),
                                   ('Physics'),
                                   ('Poetry'),
                                   ('Revolutionary Period (1775-1800)'),
                                   ('Romance'),
                                   ('Science'),
                                   ('Science Fiction'),
                                   ('Sports'),
                                   ('Travel'),
                                   ('United States'),
                                   ('Women Authors');
INSERT INTO book_category (book_id, category_id) VALUES (1, 26),
                                                        (1, 1),
                                                        (1, 11),
                                                        (2, 26),
                                                        (2, 4),
                                                        (3, 26),
                                                        (3, 9),
                                                        (4, 8),
                                                        (4, 28),
                                                        (5, 11),
                                                        (5, 12),
                                                        (5, 22),
                                                        (5, 10),
                                                        (6, 23),
                                                        (6, 19),
                                                        (6, 11),
                                                        (7, 14),
                                                        (7, 6),
                                                        (8, 15),
                                                        (8, 3),
                                                        (10, 24),
                                                        (10, 11),
                                                        (10, 10),
                                                        (11, 13),
                                                        (11, 27),
                                                        (11, 5),
                                                        (12, 18),
                                                        (12, 7),
                                                        (12, 11),
                                                        (14, 10),
                                                        (14, 16),
                                                        (15, 10),
                                                        (15, 16),
                                                        (16, 11),
                                                        (16, 17),
                                                        (17, 20),
                                                        (17, 2),
                                                        (17, 11),
                                                        (18, 10),
                                                        (18, 25),
                                                        (19, 10),
                                                        (19, 11),
                                                        (20, 27),
                                                        (20, 13),
                                                        (20, 21);
